### PR TITLE
Release Dev 2.0.0.

### PR DESCRIPTION
**Pull request by tahabasri**
- Use `globalState` as default snippets location.
- Enable sync using VSCode API.
- Refresh snippets across multiple open workspaces in more efficient way.
- Add Github Actions to automate Code Analysis.

### CODE REVIEW

**Comment by olivierverwoerd** [comment]
May I add to this that the reason for workspace snippets is so important is to allow shared snippets.
This way new snippets only have to be created once by someone in a team instead of everyone needing to make the same snippet separately.

**Comment by tahabasri** [comment]
> May I add to this that the reason for workspace snippets is so important is to allow shared snippets.
> This way new snippets only have to be created once by someone in a team instead of everyone needing to make the same snippet separately.
> 
> As an added bonus, it might help to let people know about the extension and start to use it without even having to set it up.
> 
> I would advice to keep the option to save it to the workspace as is.

indeed @olivierverwoerd, I mentioned in my comment before that I would like to keep that option available as it is really useful to dev people. 

To summarize :
- new behavior will be not using a json file on the filesystem but instead the `globalState` of the extension. This will enable sync using VSCode sync API (which is perfect to all users).
- if option `"snippets.useWorkspaceFolder"` is enabled, it will read file inside `.vscode` folder. I suggest that the extension look up for file `.vscode/snippets.json` automatically instead of relying on value of `"snippets.snippetsLocation"`, I'm thinking about deprecating the latter to avoid confusions once for all. Also, extension should mention **clearly** that using option `useWorspaceFolder` will delegate synchronization to final user (using Git, other VCS.).

If it looks good, I'll work on adapting your latest changes here. Let me know please what you think. Thanks !

**Comment by olivierverwoerd** [comment]
@tahabasri Ah I see. I saw you removed the `"snippets.useWorkspaceFolder": true` in the docs so i was a bit confused.
As long as the workspace folder can be used I'm more than happy. 😄

**Comment by DamienMrtl** [comment]
I hope this version will be ready soon ?
Actually it is bugged when using Windows and Linux subsystem so I can't use the extention.

**Comment by tahabasri** [comment]
Thanks @DamienMrtl for the feedback.
> Actually it is bugged when using Windows and Linux subsystem so I can't use the extention.

Which version is the bugged one ? 1.x or currently under dev 2.0 ?

**Comment by DamienMrtl** [comment]
> Which version is the bugged one ? 1.x or currently under dev 2.0 ?
Under 1.x

**Comment by DamienMrtl** [comment]
> Thanks @DamienMrtl for the feedback.
> 
> > Actually it is bugged when using Windows and Linux subsystem so I can't use the extention.
> 
> Which version is the bugged one ? 1.x or currently under dev 2.0 ?

The version 1.x is bugged, can we expect the version 2 to be released soon ?

**Comment by tahabasri** [comment]
I was confused with the logic behind **Settings Sync** feature as it was always overriding my remote changes with local ones. This is clearly mentioned in https://github.com/microsoft/vscode/issues/109388#issuecomment-717512236 and the root cause is that the version I'm working on is not yet published 🤷‍♂️. I'm publishing this version as preview release and will test the sync.

**Pull request merged**
